/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package roombookingsystem;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class ManageBookingGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageBookingGUI.class.getName());

    /**
     * Creates new form ManageBookingGUI
     */
    ArrayList<RoomBooking> bookingList = new ArrayList<>();

    public ManageBookingGUI() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#EAF4F4"));

        //making these labels and text fields not visible, when you click search they will appear
        roomNoLbl.setVisible(false);
        roomNoTf.setVisible(false);
        startTimeLbl.setVisible(false);
        startTimeTf.setVisible(false);
        endTimeLbl.setVisible(false);
        endTimeTf.setVisible(false);
        //loads array list that we have saved with bookings as soon as the gui is loaded

        try {
            File inFile = new File("output.dat");
            FileInputStream fStream = new FileInputStream(inFile);
            ObjectInputStream oStream = new ObjectInputStream(fStream);
            //we type cast the o stream as a new array list and copy each item from that list to our array list that we will work on
            ArrayList<RoomBooking> loadedBList = (ArrayList<RoomBooking>) oStream.readObject();
            for (RoomBooking rb : loadedBList) {
                bookingList.add(rb);
            }
            oStream.close();
            System.out.println("File loaded successfully...");
        } catch (IOException e) {
            System.out.println(e);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        searchTf = new javax.swing.JTextField();
        searchLbl = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        mainBtn = new javax.swing.JButton();
        roomNoLbl = new javax.swing.JLabel();
        startTimeLbl = new javax.swing.JLabel();
        endTimeLbl = new javax.swing.JLabel();
        roomNoTf = new javax.swing.JTextField();
        startTimeTf = new javax.swing.JTextField();
        endTimeTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(2, 48, 71));
        titleLbl.setText("MANAGE BOOKING");

        searchLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        searchLbl.setForeground(new java.awt.Color(2, 48, 71));
        searchLbl.setText("Enter the booking ID:");

        searchBtn.setBackground(new java.awt.Color(0, 119, 182));
        searchBtn.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(234, 244, 244));
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        editBtn.setBackground(new java.awt.Color(0, 119, 182));
        editBtn.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(234, 244, 244));
        editBtn.setText("EDIT");
        editBtn.addActionListener(this::editBtnActionPerformed);

        cancelBtn.setBackground(new java.awt.Color(0, 119, 182));
        cancelBtn.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(234, 244, 244));
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        mainBtn.setBackground(new java.awt.Color(0, 119, 182));
        mainBtn.setFont(new java.awt.Font("Gill Sans Nova Cond Ultra Bold", 1, 18)); // NOI18N
        mainBtn.setForeground(new java.awt.Color(234, 244, 244));
        mainBtn.setText("MAIN PAGE");
        mainBtn.addActionListener(this::mainBtnActionPerformed);

        roomNoLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        roomNoLbl.setForeground(new java.awt.Color(2, 48, 71));
        roomNoLbl.setText("Room No:");

        startTimeLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        startTimeLbl.setForeground(new java.awt.Color(2, 48, 71));
        startTimeLbl.setText("Start Time:");

        endTimeLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        endTimeLbl.setForeground(new java.awt.Color(2, 48, 71));
        endTimeLbl.setText("End Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startTimeLbl)
                            .addComponent(roomNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endTimeLbl)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(roomNoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(startTimeTf, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(endTimeTf))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLbl)
                    .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNoLbl)
                    .addComponent(roomNoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startTimeLbl))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endTimeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endTimeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        //brings you back to main page
        new MainGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        //error handle if list is empty
        if (bookingList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no existing bookings at the minute!!");

        } else {
            try {
                int searchInput = Integer.parseInt(searchTf.getText());
                //will make these variables visible now and populate the text fields with the contents of each booking
                roomNoLbl.setVisible(true);
                roomNoTf.setVisible(true);
                startTimeLbl.setVisible(true);
                startTimeTf.setVisible(true);
                endTimeLbl.setVisible(true);
                endTimeTf.setVisible(true);
                boolean bookingFound = false;

                for (int i = 0; i < bookingList.size(); i++) {
                    if (bookingList.get(i).getBookingId() == searchInput) {
                        int roomNo = bookingList.get(i).getRoomNo();
                        LocalTime startTime = bookingList.get(i).getStartTime();
                        LocalTime endTime = bookingList.get(i).getEndTime();

                        roomNoTf.setText(Integer.toString(roomNo));
                        startTimeTf.setText(startTime.toString());
                        endTimeTf.setText(endTime.toString());
                        //if we find the booking id we can break out of the loop
                        bookingFound = true;
                        break;

                    }
                }
                //if not found display error msg
                if (!bookingFound) {
                    JOptionPane.showMessageDialog(null, "No booking with that ID found!");

                }
            } //error handle if user enters anything but an integer to booking id 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "You must enter an integer for the booking ID!");
            }
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        //error handle if list is empty
        if (bookingList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no existing bookings at the minute!!");

        } else {
            int searchInput = Integer.parseInt(searchTf.getText());
            boolean bookingFound = false;
            for (int i = 0; i < bookingList.size(); i++) {
                if (bookingList.get(i).getBookingId() == searchInput) {
                    bookingList.remove(i);
                    JOptionPane.showMessageDialog(null, "Booking with booking ID: " + searchInput + " has been removed!");
                    bookingFound = true;
                    //we will save to the file once the booking has been cancelled for concurrency
                    try {
                        File outFile = new File("output.dat");
                        FileOutputStream fStream = new FileOutputStream(outFile);
                        ObjectOutputStream oStream = new ObjectOutputStream(fStream);
                        oStream.writeObject(bookingList);
                        oStream.close();

                    } catch (IOException io) {
                        System.out.println(io);
                    }

                    break;
                }

            }
            //if not found display error msg

            if (!bookingFound) {
                JOptionPane.showMessageDialog(null, "No booking with that ID found!");

            }
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        //we will save to the file once the booking has been editted for concurrency
        try {
            File outFile = new File("output.dat");
            FileOutputStream fStream = new FileOutputStream(outFile);
            ObjectOutputStream oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(bookingList);
            oStream.close();

        } catch (IOException io) {
            System.out.println(io);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageBookingGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel endTimeLbl;
    private javax.swing.JTextField endTimeTf;
    private javax.swing.JButton mainBtn;
    private javax.swing.JLabel roomNoLbl;
    private javax.swing.JTextField roomNoTf;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JTextField searchTf;
    private javax.swing.JLabel startTimeLbl;
    private javax.swing.JTextField startTimeTf;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
