/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package roombookingsystem;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dhruv
 */
public class SearchGUI extends javax.swing.JFrame {

    private java.util.ArrayList<Room> rooms = new java.util.ArrayList<>();
    private java.util.ArrayList<Booking> bookings = new java.util.ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchGUI.class.getName());

    /**
     * Creates new form SearchGUI
     */
    public SearchGUI() {
        initComponents();
        
        // Placeholder text
        dateTF.setText("YYYY-MM-DD");
        startTimeTF.setText("HH:MM");
        endTimeTF.setText("HH:MM");
        capacityTF.setText("Enter capacity");

        // Light grey color (looks like placeholder)
        dateTF.setForeground(java.awt.Color.GRAY);
        startTimeTF.setForeground(java.awt.Color.GRAY);
        endTimeTF.setForeground(java.awt.Color.GRAY);
        capacityTF.setForeground(java.awt.Color.GRAY);
        
        addPlaceholder(dateTF, "YYYY-MM-DD");
        addPlaceholder(startTimeTF, "HH:MM");
        addPlaceholder(endTimeTF, "HH:MM");
        addPlaceholder(capacityTF, "Enter capacity");
        
        this.getContentPane().setBackground(Color.decode("#EAF4F4"));
        
        bookBtn.setEnabled(false);
        messageLbl.setText("");
        loadSampleData();
    }

    private void loadSampleData() {

        try {
            File file = new File("rooms.dat");

            if (file.exists()) {
                ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file));
                rooms = (ArrayList<Room>) ois.readObject();
                ois.close();
            } else {
                // Default rooms (only first time)
                rooms.add(new Room(1, 101, 10, "Active"));
                rooms.add(new Room(2, 102, 20, "Active"));
                rooms.add(new Room(3, 103, 5, "Active"));
                rooms.add(new Room(4, 104, 30, "Active"));
                rooms.add(new Room(5, 105, 15, "Active"));

                saveRoomsToFile(); // save initial data
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        dateLbl = new javax.swing.JLabel();
        startTimeLbl = new javax.swing.JLabel();
        endTimeLbl = new javax.swing.JLabel();
        capacityLbl = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        startTimeTF = new javax.swing.JTextField();
        endTimeTF = new javax.swing.JTextField();
        capacityTF = new javax.swing.JTextField();
        viewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        messageLbl = new javax.swing.JLabel();
        bookBtn = new javax.swing.JButton();
        mainBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 20)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(2, 48, 71));
        titleLbl.setText("Search and View Available Rooms");

        searchPanel.setBackground(new java.awt.Color(0, 180, 216));

        dateLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(234, 244, 244));
        dateLbl.setText("Date:");

        startTimeLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        startTimeLbl.setForeground(new java.awt.Color(234, 244, 244));
        startTimeLbl.setText("Start Time:");

        endTimeLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        endTimeLbl.setForeground(new java.awt.Color(234, 244, 244));
        endTimeLbl.setText("End Time:");

        capacityLbl.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 14)); // NOI18N
        capacityLbl.setForeground(new java.awt.Color(234, 244, 244));
        capacityLbl.setText("Capacity:");

        dateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(endTimeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(endTimeTF))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(capacityLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(capacityTF))))
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(searchPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(startTimeLbl)
                            .addGap(18, 18, 18)
                            .addComponent(startTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, searchPanelLayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(dateLbl)
                            .addGap(18, 18, 18)
                            .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLbl)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeLbl)
                    .addComponent(startTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endTimeLbl)
                    .addComponent(endTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacityLbl))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        viewPanel.setBackground(new java.awt.Color(0, 180, 216));

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room ID", "Room No", "Capacity", "Start Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTable);

        bookBtn.setBackground(new java.awt.Color(0, 119, 182));
        bookBtn.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 16)); // NOI18N
        bookBtn.setForeground(new java.awt.Color(234, 244, 244));
        bookBtn.setText("Book Selected Room");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        mainBtn.setBackground(new java.awt.Color(0, 119, 182));
        mainBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        mainBtn.setForeground(new java.awt.Color(234, 244, 244));
        mainBtn.setText("Main Page");
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bookBtn)
                        .addGap(18, 18, 18)
                        .addComponent(mainBtn))
                    .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(viewPanelLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(viewPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(messageLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        searchBtn.setBackground(new java.awt.Color(0, 119, 182));
        searchBtn.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 16)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(234, 244, 244));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(titleLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleLbl)
                .addGap(30, 30, 30)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(searchBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTFActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a room from the table.");
            return;
        }
        
        String status = viewTable.getValueAt(selectedRow, 3).toString();
        if (status.equals("Booked")) {
            JOptionPane.showMessageDialog(this,
                "This room is already booked!");
            return;
        }

        int roomNumber = (int) viewTable.getValueAt(selectedRow, 1);
        
        String date = dateTF.getText().trim();
        String startTime = startTimeTF.getText();
        String endTime = endTimeTF.getText();

        try {
            File file = new File("output.dat");
            ArrayList<RoomBooking> bookingList = new ArrayList<>();

            if (file.exists()) {
                ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file));
                bookingList = (ArrayList<RoomBooking>) ois.readObject();
                ois.close();
            }

            // Generate new Booking ID
            int newId = bookingList.size() + 1;

            //Create new booking
            Room room = new Room(roomNumber);
            RoomBooking newBooking = new RoomBooking(
                    newId,
                    room,
                    java.time.LocalDate.parse(date),
                    java.time.LocalTime.parse(startTime),
                    java.time.LocalTime.parse(endTime),
                    java.time.LocalDateTime.now()
            );

            bookingList.add(newBooking);

            //Save to file
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(file));
            oos.writeObject(bookingList);
            oos.close();

            JOptionPane.showMessageDialog(this,
                    "Room booked successfully!\nBooking ID: " + newId);

        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error booking room!");
            e.printStackTrace();
        }

    }//GEN-LAST:event_bookBtnActionPerformed

    
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String date = dateTF.getText().trim();
        String startTime = startTimeTF.getText().trim();
        String endTime = endTimeTF.getText().trim();
        String capacityText = capacityTF.getText().trim();
        
        ArrayList<RoomBooking> bookingList = new ArrayList<>();
        try {
            File file = new File("output.dat");

            if (file.exists()) {
                ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file));
                bookingList = (ArrayList<RoomBooking>) ois.readObject();
                ois.close();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

// Check empty fields
        if (date.isEmpty() || startTime.isEmpty() || endTime.isEmpty() || capacityText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "All fields are required.", "Invalid Input",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate date format YYYY-MM-DD
        if (!date.matches("\\d{4}-\\d{2}-\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Date must be in format YYYY-MM-DD (e.g. 2026-04-01).",
                    "Invalid Date", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate date is a real date
        try {
            String[] parts = date.split("-");
            int month = Integer.parseInt(parts[1]);
            int day = Integer.parseInt(parts[2]);
            if (month < 1 || month > 12 || day < 1 || day > 31) {
                throw new Exception();
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter a valid date.",
                    "Invalid Date", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate time format HH:MM
        if (!startTime.matches("\\d{2}:\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Start time must be in format HH:MM (e.g. 09:00).",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!endTime.matches("\\d{2}:\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "End time must be in format HH:MM (e.g. 11:00).",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate time values are real times
        String[] startParts = startTime.split(":");
        String[] endParts = endTime.split(":");
        int startHour = Integer.parseInt(startParts[0]);
        int startMin = Integer.parseInt(startParts[1]);
        int endHour = Integer.parseInt(endParts[0]);
        int endMin = Integer.parseInt(endParts[1]);

        if (startHour < 0 || startHour > 23 || startMin < 0 || startMin > 59) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Start time is not a valid time.",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (endHour < 0 || endHour > 23 || endMin < 0 || endMin > 59) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "End time is not a valid time.",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate end time is after start time
        if (startTime.compareTo(endTime) >= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "End time must be after start time.",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate capacity is a positive number
        int capacity;
        try {
            capacity = Integer.parseInt(capacityText);
            if (capacity <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Capacity must be a positive number.",
                        "Invalid Capacity", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Capacity must be a number.",
                    "Invalid Capacity", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Search available rooms
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"Room ID", "Room No", "Capacity", "Status"}, 0);

        for (Room room : rooms) {
            if (room.getCapacity() >= capacity && room.getStatus().equals("Active")) {
                boolean isBooked = false;
                
                for (RoomBooking b : bookingList) {

                    if (b.getRoomNo() == room.getRoomNumber()
                        && b.getBookingDate().equals(java.time.LocalDate.parse(date))
                        && b.getStatus().equals("Booked")) {

                        if (!(b.getEndTime().toString().compareTo(startTime) <= 0 ||
                              b.getStartTime().toString().compareTo(endTime) >= 0)) {

                            isBooked = true;
                            break;
                        }
                    }
                }

                //SHOW BOTH AVAILABLE + BOOKED
                model.addRow(new Object[]{
                    room.getRoomId(),
                    room.getRoomNumber(),
                    room.getCapacity(),
                    isBooked ? "Booked" : "Available"
                });
            }
        }

        viewTable.setModel(model);

        if (model.getRowCount() == 0) {

            int choice = JOptionPane.showConfirmDialog(this,
                    "No rooms available.\nDo you want to create a new room?",
                    "No Rooms Found",
                    JOptionPane.YES_NO_OPTION);

            if (choice == JOptionPane.YES_OPTION) {

                try {
                    int capacityNew = Integer.parseInt(capacityTF.getText());

                    //Generate new Room ID
                    int newRoomId = rooms.size() + 1;

                    //Generate new Room Number
                    int newRoomNumber = 100 + newRoomId;

                    //Create new room
                    Room newRoom = new Room(newRoomId, newRoomNumber, capacityNew, "Active");

                    rooms.add(newRoom);
                    saveRoomsToFile();
                    loadRoomsFromFile();
                    searchBtn.doClick(); // refresh table

                    JOptionPane.showMessageDialog(this,
                            "New Room Created!\nRoom No: " + newRoomNumber);

                    // Add to table immediately
                    model.addRow(new Object[]{
                        newRoom.getRoomId(),
                        newRoom.getRoomNumber(),
                        newRoom.getCapacity(),
                        newRoom.getStatus()
                    });

                    viewTable.setModel(model);
                    bookBtn.setEnabled(true);
                    messageLbl.setText("1 room created and available.");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Error creating room.");
                }

            } else {
                messageLbl.setText("No rooms available for the selected criteria.");
                bookBtn.setEnabled(false);
            }

        } else {
            messageLbl.setText(model.getRowCount() + " room(s) found.");
            bookBtn.setEnabled(true);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        //brings you back to main page
        new MainGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchGUI().setVisible(true));
    }
    
    private void addPlaceholder(javax.swing.JTextField field, String placeholder) {

    field.addFocusListener(new java.awt.event.FocusAdapter() {

        public void focusGained(java.awt.event.FocusEvent evt) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(java.awt.Color.BLACK);
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (field.getText().isEmpty()) {
                field.setText(placeholder);
                field.setForeground(java.awt.Color.GRAY);
            }
        }
    });
}
    private void saveRoomsToFile() {
        try {
            File file = new File("rooms.dat");
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(file));
            oos.writeObject(rooms);
            oos.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void loadRoomsFromFile() {
    try {
        File file = new File("rooms.dat");

        if (file.exists()) {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file));
            rooms = (ArrayList<Room>) ois.readObject();
            ois.close();
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private javax.swing.JLabel capacityLbl;
    private javax.swing.JTextField capacityTF;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTF;
    private javax.swing.JLabel endTimeLbl;
    private javax.swing.JTextField endTimeTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainBtn;
    private javax.swing.JLabel messageLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel startTimeLbl;
    private javax.swing.JTextField startTimeTF;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
