/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package roombookingsystem;

/**
 *
 * @author dhruv
 */
public class SearchGUI extends javax.swing.JFrame {

    private java.util.ArrayList<Room> rooms = new java.util.ArrayList<>();
    private java.util.ArrayList<Booking> bookings = new java.util.ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchGUI.class.getName());

    /**
     * Creates new form SearchGUI
     */
    public SearchGUI() {
        initComponents();
        bookBtn.setEnabled(false);
        messageLbl.setText("");
        loadSampleData();
    }

    private void loadSampleData() {
        rooms.add(new Room(1, 101, 10, "Active"));
        rooms.add(new Room(2, 102, 20, "Active"));
        rooms.add(new Room(3, 103, 5, "Active"));
        rooms.add(new Room(4, 104, 30, "Active"));
        rooms.add(new Room(5, 105, 15, "Active"));
        bookings.add(new Booking(1, "John", "S001", 1, "2026-04-01", "09:00", "11:00", "Active"));
        bookings.add(new Booking(2, "Sarah", "S002", 3, "2026-04-01", "10:00", "12:00", "Active"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        dateLbl = new javax.swing.JLabel();
        startTimeLbl = new javax.swing.JLabel();
        endTimeLbl = new javax.swing.JLabel();
        capacityLbl = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        startTimeTF = new javax.swing.JTextField();
        endTimeTF = new javax.swing.JTextField();
        capacityTF = new javax.swing.JTextField();
        viewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        messageLbl = new javax.swing.JLabel();
        bookBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setText("Search and View Available Rooms");

        dateLbl.setText("Date:");

        startTimeLbl.setText("Start Time:");

        endTimeLbl.setText("End Time:");

        capacityLbl.setText("Capacity:");

        dateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(capacityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(capacityTF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addComponent(endTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(endTimeTF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addComponent(startTimeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(startTimeTF))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLbl)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeLbl)
                    .addComponent(startTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endTimeLbl)
                    .addComponent(endTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacityLbl)
                    .addComponent(capacityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room ID", "Room No", "Capacity", "Start Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTable);

        bookBtn.setText("Book Selected Room");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bookBtn)
                .addGap(65, 65, 65))
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(messageLbl)
                .addGap(27, 27, 27)
                .addComponent(bookBtn)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(titleLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(searchBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(47, 47, 47)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn)
                .addGap(18, 18, 18)
                .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTFActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a room from the table.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int roomNumber = (int) viewTable.getValueAt(selectedRow, 1);
        javax.swing.JOptionPane.showMessageDialog(this,
                "Proceeding to book Room " + roomNumber);
    }//GEN-LAST:event_bookBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String date = dateTF.getText().trim();
        String startTime = startTimeTF.getText().trim();
        String endTime = endTimeTF.getText().trim();
        String capacityText = capacityTF.getText().trim();

// Check empty fields
        if (date.isEmpty() || startTime.isEmpty() || endTime.isEmpty() || capacityText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "All fields are required.", "Invalid Input",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate date format YYYY-MM-DD
        if (!date.matches("\\d{4}-\\d{2}-\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Date must be in format YYYY-MM-DD (e.g. 2026-04-01).",
                    "Invalid Date", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate date is a real date
        try {
            String[] parts = date.split("-");
            int month = Integer.parseInt(parts[1]);
            int day = Integer.parseInt(parts[2]);
            if (month < 1 || month > 12 || day < 1 || day > 31) {
                throw new Exception();
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter a valid date.",
                    "Invalid Date", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate time format HH:MM
        if (!startTime.matches("\\d{2}:\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Start time must be in format HH:MM (e.g. 09:00).",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!endTime.matches("\\d{2}:\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "End time must be in format HH:MM (e.g. 11:00).",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate time values are real times
        String[] startParts = startTime.split(":");
        String[] endParts = endTime.split(":");
        int startHour = Integer.parseInt(startParts[0]);
        int startMin = Integer.parseInt(startParts[1]);
        int endHour = Integer.parseInt(endParts[0]);
        int endMin = Integer.parseInt(endParts[1]);

        if (startHour < 0 || startHour > 23 || startMin < 0 || startMin > 59) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Start time is not a valid time.",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (endHour < 0 || endHour > 23 || endMin < 0 || endMin > 59) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "End time is not a valid time.",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate end time is after start time
        if (startTime.compareTo(endTime) >= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "End time must be after start time.",
                    "Invalid Time", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validate capacity is a positive number
        int capacity;
        try {
            capacity = Integer.parseInt(capacityText);
            if (capacity <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Capacity must be a positive number.",
                        "Invalid Capacity", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Capacity must be a number.",
                    "Invalid Capacity", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

// Search available rooms
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"Room ID", "Room No", "Capacity", "Status"}, 0);

        for (Room room : rooms) {
            if (room.getCapacity() >= capacity && room.getStatus().equals("Active")) {
                boolean isBooked = false;
                for (Booking b : bookings) {
                    if (b.getRoomId() == room.getRoomId()
                            && b.getDate().equals(date)
                            && b.getStatus().equals("Active")
                            && !(b.getEndTime().compareTo(startTime) <= 0
                            || b.getStartTime().compareTo(endTime) >= 0)) {
                        isBooked = true;
                        break;
                    }
                }
                if (!isBooked) {
                    model.addRow(new Object[]{
                        room.getRoomId(),
                        room.getRoomNumber(),
                        room.getCapacity(),
                        room.getStatus()
                    });
                }
            }
        }

        viewTable.setModel(model);

        if (model.getRowCount() == 0) {
            messageLbl.setText("No rooms available for the selected criteria.");
            bookBtn.setEnabled(false);
        } else {
            messageLbl.setText(model.getRowCount() + " room(s) found.");
            bookBtn.setEnabled(true);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private javax.swing.JLabel capacityLbl;
    private javax.swing.JTextField capacityTF;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTF;
    private javax.swing.JLabel endTimeLbl;
    private javax.swing.JTextField endTimeTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel startTimeLbl;
    private javax.swing.JTextField startTimeTF;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
